# Generated by Django 2.2 on 2020-01-25 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['date']},
        ),
    ]
